language: generic
sudo: false

cache:
  apt: true
  timeout: 10000
  directories: build

script:
- mkdir -p build
- pdflatex -interaction=nonstopmode -output-directory build skrypt.tex || exit 0

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

addons:
  apt:
    packages:
    - pgf
    - texlive-fonts-extra
    - texlive-fonts-recommended
    - texlive-generic-recommended
    - texlive-lang-polish
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-pictures
    - texlive-science
